---
name: "Publish"

"on":
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: test-kitchen/.github/.github/workflows/publish.yml@main
    secrets: inherit
